### ISSUE TITLE
Create multi-networkpolicy-iptables (or something like that) to keep API only in this repository

### ISSUE THREAD

**Issue by s1061123** [k8snetworkplumbingwg/multi-networkpolicy#12]
I got some feedback about the repository, to make current code separate from implementation and APIs for further implementation, as follows:

- k8snetworkplumbingwg/multi-networkpolicy (API and library)
- k8snetworkplumbingwg/multi-networkpolicy-iptables (iptable-based implementation)
- k8snetworkplumbingwg/multi-networkpolicy-foobar-some-awesome (another one)

+1 to the comment, so think about it. It would be discussed in next NPWG meeting.

**Comment by nvetel** [comment]
Hello @s1061123,

I'm currently thinking of using multi-networkpolicies to implement Kubernetes NetworkPolicies for VPP ACLs.
After looking at iptables and tc implementations, it appears to me that a significant part of the code could be reused and took out from those implementation, and put in the main multi-networkpolicy project or another one.

By a significant part of the code, I mean all the logic tracking for changes in different kind of resources, and triggering the implementation-specific logic which is rendering and applying the rules.

Is there any will/project to do so ?

Thanks

**Comment by s1061123** [comment]
Hi @nvetel, thank you for your comments. Currently this repository is only for Kubernetes client (generated by client generator) for multi-networkpolicy and I don't want to add other codes, including util code, in this repository.

I understand that you may feel that some code from iptables/tc could be reused, however, actually it will make each repository code complicated and dependencies (i.e. packet forwarding mechanism/packet API is not shared among VPP/netlink/iptables/nft/tc). Previously I have various experiences such like that. Now I prefer less dependency in the repository actually, hence I don't have any will to make utilities for that.

**Comment by s1061123** [comment]
BTW, I will close this issue because now multi-networkpolicy-iptables was created as well as tc implementation.

**Comment by nvetel** [comment]
Thanks for your feedback @s1061123  !

Of course I was not talking of sharing packet/ACL/rules implementation in a library, but only the Kubernetes API interaction (watch and react to events), leaving the implementation makers customize what is done in reaction to an event.

Anyway, I understand that it can be a tricky initiative sometimes, and not necessirally a benefit one in the end.

Thanks !
